# Generated by Django 4.2.8 on 2026-02-16 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleflag",
            options={"ordering": ["-flagged_at"]},
        ),
        migrations.RenameField(
            model_name="vehicleflag",
            old_name="created_at",
            new_name="flagged_at",
        ),
        migrations.RemoveField(
            model_name="vehicleflag",
            name="alert_on_entry",
        ),
        migrations.RemoveField(
            model_name="vehicleflag",
            name="email_recipients",
        ),
        migrations.RemoveField(
            model_name="vehicleflag",
            name="site_name",
        ),
        migrations.AddField(
            model_name="vehicleflag",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleflag",
            name="resolution_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleflag",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flags_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vehicleflag",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Flag"),
                    ("no_exit", "No Exit Record"),
                    ("overstay", "Overstay (>24h)"),
                    ("rapid_movement", "Rapid Multi-Site Movement"),
                    ("frequent_visitor", "Unusual Visit Frequency"),
                    ("payment_issue", "Payment Discrepancy"),
                    ("custom", "Custom Rule"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="vehicleflag",
            name="sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="vehicleflag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleflag",
            name="flagged_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flags_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleflag",
            name="plate_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicleflag",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleflag",
            name="reason",
            field=models.CharField(max_length=200),
        ),
    ]
