# Generated by Django 4.2.8 on 2026-02-16 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_alter_vehicleflag_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("no_exit", "Vehicle has no exit record"),
                            ("overstay", "Vehicle overstays (duration > threshold)"),
                            ("visit_count", "Visit frequency exceeds threshold"),
                            ("rapid_movement", "Visits multiple sites rapidly"),
                            ("specific_site", "Vehicle enters specific site"),
                            ("time_based", "Vehicle enters during specific time"),
                            ("plate_pattern", "Plate matches pattern"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("threshold_hours", models.IntegerField(blank=True, null=True)),
                ("threshold_count", models.IntegerField(blank=True, null=True)),
                ("threshold_sites", models.IntegerField(blank=True, null=True)),
                (
                    "target_site",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                (
                    "plate_pattern",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("send_email", models.BooleanField(default=True)),
                ("send_sms", models.BooleanField(default=False)),
                ("email_recipients", models.TextField(blank=True, null=True)),
                ("sms_recipients", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_alert_rules",
                "ordering": ["-created_at"],
            },
        ),
    ]
